In [1]:
import pandas as pd

In [1]:
# Build merged data from DB_bank
from pathlib import Path

cwd = Path.cwd()
if (cwd / "DB_bank").exists():
    base = cwd / "DB_bank"
elif (cwd.parent / "DB_bank").exists():
    base = cwd.parent / "DB_bank"
else:
    raise FileNotFoundError("DB_bank not found. Update the base path.")

customers = pd.read_csv(base / "customers.csv")
accounts = pd.read_csv(base / "accounts.csv")
transactions = pd.read_csv(base / "transactions.csv")
str_df = pd.read_csv(base / "str.csv")

# Parse dates and numeric fields
customers["dob_or_incorporation_date"] = pd.to_datetime(
    customers["dob_or_incorporation_date"], errors="coerce"
)

for col in ["account_open_date", "last_dormant_date", "account_close_date"]:
    accounts[col] = pd.to_datetime(accounts[col], errors="coerce")

transactions["transaction_datetime"] = pd.to_datetime(
    transactions["transaction_datetime"], errors="coerce"
)
transactions["transaction_amount"] = pd.to_numeric(
    transactions["transaction_amount"], errors="coerce"
)

str_df["str_filed_date"] = pd.to_datetime(str_df["str_filed_date"], errors="coerce")

# Ensure only one STR per account_id (keep earliest)
str_df = (
    str_df
    .sort_values(["account_id", "str_filed_date"])
    .drop_duplicates(subset=["account_id"], keep="first")
)

# Merge: transactions -> accounts -> customers -> str
accounts_core = accounts.drop(columns=["customer_id"])
new_merged_data = (
    transactions
    .merge(accounts_core, on="account_id", how="left")
    .merge(customers, on="customer_id", how="left")
    .merge(str_df, on="account_id", how="left")
)

new_merged_data["str_filed_flag"] = new_merged_data["str_filed_date"].notna().astype("int8")

FileNotFoundError: DB_bank not found. Update the base path.

In [3]:
new_merged_data

,transaction_id,account_id,customer_id,transaction_datetime,transaction_type,transaction_category,transaction_amount,account_type,account_open_date,account_status,...,income_bracket,kyc_status,pep_flag,sanction_flag,internal_watchlist_flag,customer_risk_rating,dob_or_incorporation_date,customer_segment,str_filed_date,str_filed_flag
0,TXN_00000000,ACC_002137,CUST_01705,2024-07-07,DEBIT,RTGS,697775.69,SAVINGS,1965-05-07,ACTIVE,...,<5L,KYC_COMPLETE,N,N,N,LOW,1980-12-25,RETAIL,NaT,0
1,TXN_00000001,ACC_001962,CUST_01561,2024-12-21,DEBIT,CHEQUE,2109666.91,SAVINGS,1960-03-19,ACTIVE,...,5-10L,KYC_COMPLETE,N,N,N,MEDIUM,1960-06-16,RETAIL,NaT,0
2,TXN_00000002,ACC_000579,CUST_00467,2024-07-24,DEBIT,CHEQUE,994268.37,SAVINGS,2010-09-28,ACTIVE,...,<5L,KYC_COMPLETE,N,N,N,LOW,2003-09-25,RETAIL,NaT,0
3,TXN_00000003,ACC_008046,CUST_06436,2024-08-26,CREDIT,FX,4346514.67,SAVINGS,1991-12-05,ACTIVE,...,10-25L,KYC_COMPLETE,N,N,N,LOW,1965-11-14,RETAIL,NaT,0
4,TXN_00000004,ACC_003043,CUST_02444,2024-12-26,CREDIT,RTGS,1076647.28,SAVINGS,2006-07-14,ACTIVE,...,<5L,KYC_COMPLETE,N,N,N,LOW,1967-12-21,RETAIL,NaT,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,TXN_00249995,ACC_002039,CUST_01620,2024-11-01,CREDIT,IMPS,318211.98,SAVINGS,2004-01-09,ACTIVE,...,<5L,KYC_COMPLETE,N,N,N,MEDIUM,1938-07-24,RETAIL,NaT,0
249996,TXN_00249996,ACC_005537,CUST_04439,2024-07-14,CREDIT,NEFT,3109135.17,SAVINGS,1965-04-28,ACTIVE,...,<5L,KYC_COMPLETE,N,N,N,HIGH,1951-06-01,RETAIL,2024-11-07,1
249997,TXN_00249997,ACC_004268,CUST_03413,2024-07-06,CREDIT,NEFT,2638231.05,SAVINGS,1976-09-18,ACTIVE,...,<5L,KYC_COMPLETE,N,N,N,LOW,1958-08-09,RETAIL,NaT,0
249998,TXN_00249998,ACC_004998,CUST_03994,2024-10-17,CREDIT,NEFT,3930338.42,SAVINGS,1963-03-19,ACTIVE,...,<5L,KYC_COMPLETE,N,N,N,HIGH,1973-05-07,RETAIL,NaT,0
249999,TXN_00249999,ACC_000198,CUST_00161,2024-10-01,DEBIT,NEFT,1164071.44,SAVINGS,2001-11-16,ACTIVE,...,<5L,EXPIRED,N,N,N,LOW,1951-07-03,RETAIL,NaT,0

In [7]:
new_merged_data['transaction_datetime'] = pd.to_datetime(
    new_merged_data['transaction_datetime'],
    errors='coerce'
)

# -------------------------------------------------------------------
# STEP 0 – sanity check
# -------------------------------------------------------------------

In [11]:
step0 = (
    new_merged_data
    .loc[
        (new_merged_data['account_id'] == 'ACC_000001') &
        (new_merged_data['transaction_type'] == 'DEBIT')
    ,
        ['transaction_datetime', 'transaction_amount']
    ]
    .sort_values('transaction_datetime')
)

print("STEP 0 - sanity check (ACC_000001, DEBIT):")
step0.head(20)

STEP 0 - sanity check (ACC_000001, DEBIT):

       transaction_datetime  transaction_amount
236809           2024-07-01            44281.22
93156            2024-09-12          1210456.35
183660           2024-09-21            26207.81
113122           2024-09-27          2165984.21
183468           2024-12-07            34297.13

# -------------------------------------------------------------------
# STEP 1 – static filter: only DEBIT transactions
# -------------------------------------------------------------------

In [13]:
step1_monthly = new_merged_data[new_merged_data['transaction_type'] == 'DEBIT'].copy()

print("\nSTEP 1 - row count (DEBIT only):", len(step1_monthly))
print("\nSTEP 1 - sample:")
step1_monthly.sort_values(['account_id', 'transaction_datetime']).head(5)

STEP 1 - row count (DEBIT only): 125115

STEP 1 - sample:

,transaction_id,account_id,customer_id,transaction_datetime,transaction_type,transaction_category,transaction_amount,accounts.account_id,accounts.customer_id,accounts.account_type,...,customers.income_bracket,customers.kyc_status,customers.pep_flag,customers.sanction_flag,customers.internal_watchlist_flag,customers.customer_risk_rating,customers.dob_or_incorporation_date,customers.customer_segment,str.account_id,str.str_filed_date
236809,TXN_00235831,ACC_000001,CUST_00001,2024-07-01,DEBIT,CASH,44281.22,ACC_000001,CUST_00001,SAVINGS,...,<5L,KYC_COMPLETE,N,N,N,LOW,09/03/1950,RETAIL,NaN,NaN
93156,TXN_00092771,ACC_000001,CUST_00001,2024-09-12,DEBIT,FX,1210456.35,ACC_000001,CUST_00001,SAVINGS,...,<5L,KYC_COMPLETE,N,N,N,LOW,09/03/1950,RETAIL,NaN,NaN
183660,TXN_00182883,ACC_000001,CUST_00001,2024-09-21,DEBIT,CASH,26207.81,ACC_000001,CUST_00001,SAVINGS,...,<5L,KYC_COMPLETE,N,N,N,LOW,09/03/1950,RETAIL,NaN,NaN
113122,TXN_00112646,ACC_000001,CUST_00001,2024-09-27,DEBIT,INTERNATIONAL_WIRE,2165984.21,ACC_000001,CUST_00001,SAVINGS,...,<5L,KYC_COMPLETE,N,N,N,LOW,09/03/1950,RETAIL,NaN,NaN
183468,TXN_00182691,ACC_000001,CUST_00001,2024-12-07,DEBIT,CASH,34297.13,ACC_000001,CUST_00001,SAVINGS,...,<5L,KYC_COMPLETE,N,N,N,LOW,09/03/1950,RETAIL,NaN,NaN

# -------------------------------------------------------------------
# STEP 1.5 – grouping at daily level
# (Here you group by the full transaction_datetime in SQL; we mimic that)
# -------------------------------------------------------------------

In [27]:
step_2_5_daily_level = (
    step1_monthly
    .assign(
        month_last_date = step1_monthly['transaction_datetime'].dt.to_period('M').dt.to_timestamp('M') + pd.Timedelta(days=1)
        # SQL: DATEADD(day, 1, EOMONTH(transaction_datetime))
    )
    .groupby(['account_id', 'customer_id', 'transaction_datetime', 'month_last_date'], as_index=False)
    .agg(total_daily_amount=('transaction_amount', 'sum'))
)

print("\nSTEP 1.5 - daily level for ACC_000001:")
step_2_5_daily_level.loc[step_2_5_daily_level['account_id'] == 'ACC_000001'].sort_values('transaction_datetime')

STEP 1.5 - daily level for ACC_000001:

,account_id,customer_id,transaction_datetime,month_last_date,total_daily_amount
0,ACC_000001,CUST_00001,2024-07-01,2024-08-01,44281.22
1,ACC_000001,CUST_00001,2024-09-12,2024-10-01,1210456.35
2,ACC_000001,CUST_00001,2024-09-21,2024-10-01,26207.81
3,ACC_000001,CUST_00001,2024-09-27,2024-10-01,2165984.21
4,ACC_000001,CUST_00001,2024-12-07,2025-01-01,34297.13

# -------------------------------------------------------------------
# STEP 2.1 – lookback on 7 days (daily - transaction_datetime column)
# Left join step_2_5_daily_level (a) with step_2_5_daily_level (b)
# where account_id matches and b.transaction_datetime between
# a.transaction_datetime - 7 days and a.transaction_datetime
# -------------------------------------------------------------------

In [16]:
a = step_2_5_daily_level.rename(columns={
    'transaction_datetime': 'transaction_datetime_a',
    'total_daily_amount': 'total_daily_amount_a'
})

In [18]:
b = step_2_5_daily_level.rename(columns={
    'transaction_datetime': 'transaction_datetime_b',
    'total_daily_amount': 'total_daily_amount_b'
})

In [20]:
merged_ab = a.merge(
    b,
    on='account_id',
    suffixes=('_a', '_b'),
    how='left'
)

# Filter on the 7-day lookback window
mask_7d = (
    (merged_ab['transaction_datetime_b'] >= merged_ab['transaction_datetime_a'] - pd.Timedelta(days=7)) &
    (merged_ab['transaction_datetime_b'] <= merged_ab['transaction_datetime_a'])
)

step3_lookback_table = (
    merged_ab.loc[mask_7d, [
        'account_id',
        'customer_id_a',
        'transaction_datetime_a',
        'total_daily_amount_a',
        'total_daily_amount_b',
        'transaction_datetime_b'
    ]]
    .rename(columns={
        'customer_id_a': 'customer_id',
        'transaction_datetime_a': 'transaction_datetime',
        'total_daily_amount_a': 'total_daily_amount',
        'total_daily_amount_b': 'amount_lookback',
        'transaction_datetime_b': 'trxn_date_daily_level'
    })
    .sort_values(['account_id', 'transaction_datetime', 'trxn_date_daily_level'])
)

print("\nSTEP 2.1 - 7-day lookback for ACC_000001:")
step3_lookback_table.loc[step3_lookback_table['account_id'] == 'ACC_000001'].head(50)

STEP 2.1 - 7-day lookback for ACC_000001:

,account_id,customer_id,transaction_datetime,total_daily_amount,amount_lookback,trxn_date_daily_level
0,ACC_000001,CUST_00001,2024-07-01,44281.22,44281.22,2024-07-01
6,ACC_000001,CUST_00001,2024-09-12,1210456.35,1210456.35,2024-09-12
12,ACC_000001,CUST_00001,2024-09-21,26207.81,26207.81,2024-09-21
17,ACC_000001,CUST_00001,2024-09-27,2165984.21,26207.81,2024-09-21
18,ACC_000001,CUST_00001,2024-09-27,2165984.21,2165984.21,2024-09-27
24,ACC_000001,CUST_00001,2024-12-07,34297.13,34297.13,2024-12-07

# -------------------------------------------------------------------
# STEP 2.2 – lookback on 60 days (monthly - transaction_datetime)
# Logic:
#  - For each (account_id, month_last_date), find the first row by transaction_datetime
#    (rank_1 = 1).
#  - For each row a, join to rows d where a.account_id = d.account_id and
#    a.transaction_datetime between (d.month_last_date - 60 days) and d.month_last_date.
# -------------------------------------------------------------------

In [31]:
# -------------------------------------------------------------------
# STEP 2.2 – lookback on 60 days (monthly - transaction_datetime)
# FIXED VERSION
# -------------------------------------------------------------------

# First: compute rank_1 per (account_id, month_last_date)
step_2_5_daily_level_sorted = (
    step_2_5_daily_level
    .sort_values(['account_id', 'month_last_date', 'transaction_datetime'])
)

# Get d: first row per (account_id, month_last_date)
d = (
    step_2_5_daily_level_sorted
    .drop_duplicates(subset=['account_id', 'month_last_date'], keep='first')
    [['account_id', 'customer_id', 'month_last_date']]
    .copy()
)

print("\nDEBUG - d (first row per month):")
print(d[d['account_id'] == 'ACC_000001'].head())

# Prepare a2
a2 = step_2_5_daily_level.copy()

print("\nDEBUG - a2 columns:", a2.columns.tolist())
print("\nDEBUG - a2 sample:")
print(a2[a2['account_id'] == 'ACC_000001'].head())

# Do a cross join on account_id, customer_id
# This creates month_last_date_x (from a2) and month_last_date_y (from d)
merged_a2d = a2.merge(
    d,
    on=['account_id', 'customer_id'],
    how='left',
    suffixes=('_x', '_y')
)

print("\nDEBUG - merged_a2d columns after merge:", merged_a2d.columns.tolist())
print("\nDEBUG - merged_a2d shape:", merged_a2d.shape)
print("\nDEBUG - merged_a2d sample:")
print(merged_a2d[merged_a2d['account_id'] == 'ACC_000001'].head(10))

# Apply 60-day lookback window filter
# Use month_last_date_y (from d, the reference month-end)
# and transaction_datetime (from a2, the transaction date)
mask_60d = (
    (merged_a2d['transaction_datetime'] >= merged_a2d['month_last_date_y'] - pd.Timedelta(days=60)) &
    (merged_a2d['transaction_datetime'] <= merged_a2d['month_last_date_y'])
)

print("\nDEBUG - rows passing 60d mask:", mask_60d.sum())

# Remove duplicates and create final result
step3_lookback_table_monthly = (
    merged_a2d
    .loc[mask_60d]
    .drop_duplicates(
        subset=['account_id', 'customer_id', 'transaction_datetime', 'month_last_date_y'],
        keep='first'
    )
    .rename(columns={
        'total_daily_amount': 'lookbakc_amt',
        'month_last_date_y': 'month_last_date'  # Use the reference month-end from d
    })
    [['account_id', 'customer_id', 'transaction_datetime', 'lookbakc_amt', 'month_last_date']]
    .sort_values(['account_id', 'month_last_date', 'transaction_datetime'])
    .reset_index(drop=True)
)

print("\nSTEP 2.2 - step3_lookback_table_monthly for ACC_000001:")
step3_lookback_table_monthly.loc[step3_lookback_table_monthly['account_id'] == 'ACC_000001']\
    .sort_values('month_last_date')

DEBUG - d (first row per month):
   account_id customer_id month_last_date
0  ACC_000001  CUST_00001      2024-08-01
1  ACC_000001  CUST_00001      2024-10-01
4  ACC_000001  CUST_00001      2025-01-01

DEBUG - a2 columns: ['account_id', 'customer_id', 'transaction_datetime', 'month_last_date', 'total_daily_amount']

DEBUG - a2 sample:
   account_id customer_id transaction_datetime month_last_date  \
0  ACC_000001  CUST_00001           2024-07-01      2024-08-01
1  ACC_000001  CUST_00001           2024-09-12      2024-10-01
2  ACC_000001  CUST_00001           2024-09-21      2024-10-01
3  ACC_000001  CUST_00001           2024-09-27      2024-10-01
4  ACC_000001  CUST_00001           2024-12-07      2025-01-01

   total_daily_amount
0            44281.22
1          1210456.35
2            26207.81
3          2165984.21
4            34297.13

DEBUG - merged_a2d columns after merge: ['account_id', 'customer_id', 'transaction_datetime', 'month_last_date_x', 'total_daily_amount', 'month_last_date_y']

DEBUG - merged_a2d shape: (662768, 6)

DEBUG - merged_a2d sample:
   account_id customer_id transaction_datetime month_last_date_x  \
0  ACC_000001  CUST_00001           2024-07-01        2024-08-01
1  ACC_000001  CUST_00001           2024-07-01        2024-08-01
2  ACC_000001  CUST_00001           2024-07-01        2024-08-01
3  ACC_000001  CUST_00001           2024-09-12        2024-10-01
4  ACC_000001  CUST_00001           2024-09-12        2024-10-01
5  ACC_000001  CUST_00001           2024-09-12        2024-10-01
6  ACC_000001  CUST_00001           2024-09-21        2024-10-01
7  ACC_000001  CUST_00001           2024-09-21        2024-10-01
8  ACC_000001  CUST_00001           2024-09-21        2024-10-01
9  ACC_000001  CUST_00001           2024-09-27        2024-10-01

   total_daily_amount month_last_date_y
0            44281.22        2024-08-01
1            44281.22        2024-10-01
2            44281.22        2025-01-01
3          1210456.35        2024-08-01
4          1210456.35        2024-10-01
5          1210456.35        2025-01-01
6            26207.81        2024-08-01
7            26207.81        2024-10-01
8            26207.81        2025-01-01
9          2165984.21        2024-08-01

DEBUG - rows passing 60d mask: 209521

STEP 2.2 - step3_lookback_table_monthly for ACC_000001:

   account_id customer_id transaction_datetime  lookbakc_amt month_last_date
0  ACC_000001  CUST_00001           2024-07-01      44281.22      2024-08-01
1  ACC_000001  CUST_00001           2024-09-12    1210456.35      2024-10-01
2  ACC_000001  CUST_00001           2024-09-21      26207.81      2024-10-01
3  ACC_000001  CUST_00001           2024-09-27    2165984.21      2024-10-01
4  ACC_000001  CUST_00001           2024-12-07      34297.13      2025-01-01

# -------------------------------------------------------------------
# STEP 3.1 – Daily threshold (7-day lookback)
# group by account_id, transaction_datetime, sum(amount_lookback)
# -------------------------------------------------------------------

In [32]:
daily_threshold = (
    step3_lookback_table
    .groupby(['account_id', 'transaction_datetime'], as_index=False)
    .agg(threshold_amt=('amount_lookback', 'sum'))
)

print("\nSTEP 3.1 - daily threshold for ACC_000001:")
daily_threshold.loc[daily_threshold['account_id'] == 'ACC_000001'].sort_values('transaction_datetime')

STEP 3.1 - daily threshold for ACC_000001:

   account_id transaction_datetime  threshold_amt
0  ACC_000001           2024-07-01       44281.22
1  ACC_000001           2024-09-12     1210456.35
2  ACC_000001           2024-09-21       26207.81
3  ACC_000001           2024-09-27     2192192.02
4  ACC_000001           2024-12-07       34297.13

# -------------------------------------------------------------------
# STEP 3.2 – Monthly threshold (60-day lookback)
# group by account_id, month_last_date, sum(lookbakc_amt)
# -------------------------------------------------------------------

In [34]:
monthly_threshold = (
    step3_lookback_table_monthly
    .groupby(['account_id', 'month_last_date'], as_index=False)
    .agg(threshold_amt=('lookbakc_amt', 'sum'))
)

print("\nSTEP 3.2 - monthly threshold for ACC_000001:")
monthly_threshold.loc[monthly_threshold['account_id'] == 'ACC_000001'].sort_values('month_last_date')

STEP 3.2 - monthly threshold for ACC_000001:

   account_id month_last_date  threshold_amt
0  ACC_000001      2024-08-01       44281.22
1  ACC_000001      2024-10-01     3402648.37
2  ACC_000001      2025-01-01       34297.13

In [4]:
import pandas as pd
import numpy as np
from datetime import datetime

# =====================================================================
# CONFIGURATION - CHANGE THESE PARAMETERS
# =====================================================================
TRANSACTION_TYPE = 'DEBIT'  # 'DEBIT', 'CREDIT', or 'ALL'
AGGREGATION_LEVEL = 'daily'  # 'daily' or 'monthly'
LOOKBACK_DAYS = 10 # 7, 10, 14, 20, 30, 60, 90, etc.
DEBUG = True

# =====================================================================
# STEP 0 – Load and validate data
# =====================================================================
print("="*70)
print(f"CONFIG: TYPE={TRANSACTION_TYPE}, LEVEL={AGGREGATION_LEVEL}, LOOKBACK={LOOKBACK_DAYS} days")
print("="*70)

# Ensure transaction_datetime is datetime
new_merged_data['transaction_datetime'] = pd.to_datetime(new_merged_data['transaction_datetime'])

# =====================================================================
# STEP 1 – Filter by transaction type
# =====================================================================
if TRANSACTION_TYPE == 'ALL':
    step1_filtered = new_merged_data.copy()
else:
    step1_filtered = new_merged_data[new_merged_data['transaction_type'] == TRANSACTION_TYPE].copy()

print(f"\nSTEP 1 - Row count ({TRANSACTION_TYPE}):", len(step1_filtered))
print(f"Sample:")
print(step1_filtered.sort_values(['account_id', 'transaction_datetime']).head(10))

# =====================================================================
# STEP 1.5 – Group to daily/monthly level
# =====================================================================
if AGGREGATION_LEVEL == 'daily':
    # Group by account, customer, and exact transaction_datetime
    step_daily_level = (
        step1_filtered
        .assign(
            month_last_date = step1_filtered['transaction_datetime'].dt.to_period('M').dt.to_timestamp('M') + pd.Timedelta(days=1)
        )
        .groupby(['account_id', 'customer_id', 'transaction_datetime', 'month_last_date'], as_index=False)
        .agg(total_daily_amount=('transaction_amount', 'sum'))
    )
    aggregation_key = 'transaction_datetime'
    
else:  # monthly
    # Group by account, customer, and month
    step_daily_level = (
        step1_filtered
        .assign(
            month_last_date = step1_filtered['transaction_datetime'].dt.to_period('M').dt.to_timestamp('M') + pd.Timedelta(days=1),
            month_start = step1_filtered['transaction_datetime'].dt.to_period('M').dt.to_timestamp()
        )
        .groupby(['account_id', 'customer_id', 'month_start', 'month_last_date'], as_index=False)
        .agg(total_daily_amount=('transaction_amount', 'sum'))
        .rename(columns={'month_start': 'transaction_datetime'})
    )
    aggregation_key = 'transaction_datetime'

print(f"\nSTEP 1.5 - Aggregated to {AGGREGATION_LEVEL} level: {len(step_daily_level)} rows")
print(step_daily_level.head(10))

# =====================================================================
# STEP 2 – Lookback join (PARAMETERIZED)
# =====================================================================
print(f"\nSTEP 2 - Creating {LOOKBACK_DAYS}-day lookback join...")

# Prepare a (current transactions)
a = step_daily_level.rename(columns={
    'transaction_datetime': 'transaction_datetime_a',
    'total_daily_amount': 'total_daily_amount_a'
})

# Prepare b (historical transactions for lookback)
b = step_daily_level.rename(columns={
    'transaction_datetime': 'transaction_datetime_b',
    'total_daily_amount': 'total_daily_amount_b'
})

# Merge on account_id
merged_ab = a.merge(
    b,
    on='account_id',
    suffixes=('_a', '_b'),
    how='left'
)

# Filter on lookback window
mask_lookback = (
    (merged_ab['transaction_datetime_b'] >= merged_ab['transaction_datetime_a'] - pd.Timedelta(days=LOOKBACK_DAYS)) &
    (merged_ab['transaction_datetime_b'] <= merged_ab['transaction_datetime_a'])
)

lookback_table = (
    merged_ab.loc[mask_lookback, [
        'account_id',
        'customer_id_a',
        'transaction_datetime_a',
        'total_daily_amount_a',
        'total_daily_amount_b',
        'transaction_datetime_b'
    ]]
    .rename(columns={
        'customer_id_a': 'customer_id',
        'transaction_datetime_a': 'transaction_datetime',
        'total_daily_amount_a': 'total_daily_amount',
        'total_daily_amount_b': 'amount_lookback',
        'transaction_datetime_b': 'trxn_date_lookback'
    })
    .sort_values(['account_id', 'transaction_datetime', 'trxn_date_lookback'])
)

print(f"STEP 2 - Lookback rows created: {len(lookback_table)}")

# =====================================================================
# STEP 3 – Aggregation to get thresholds
# =====================================================================
threshold_table = (
    lookback_table
    .groupby(['account_id', 'customer_id', 'transaction_datetime'], as_index=False)
    .agg(
        threshold_amt=('amount_lookback', 'sum'),
        trxn_count=('amount_lookback', 'count'),
        avg_amt=('amount_lookback', 'mean'),
        max_amt=('amount_lookback', 'max'),
        min_amt=('amount_lookback', 'min')
    )
)

print(f"\nSTEP 3 - Threshold table created: {len(threshold_table)} rows")
print(threshold_table.head(20))

# =====================================================================
# WORST CASE ANALYSIS
# =====================================================================
print("\n" + "="*70)
print("WORST CASE POPULATION ANALYSIS")
print("="*70)

worst_case = threshold_table.groupby('account_id').agg(
    count_periods=('account_id', 'count'),
    total_threshold=('threshold_amt', 'sum'),
    avg_threshold=('threshold_amt', 'mean'),
    max_threshold=('threshold_amt', 'max'),
    min_threshold=('threshold_amt', 'min'),
    total_trxn_count=('trxn_count', 'sum')
).reset_index().sort_values('total_threshold', ascending=False)

print(f"\nTop 20 accounts by total threshold amount:")
print(worst_case.head(20))

print(f"\nWorst case (highest single threshold):")
worst_single = threshold_table.nlargest(10, 'threshold_amt')[['account_id', 'customer_id', 'transaction_datetime', 'threshold_amt', 'trxn_count']]
print(worst_single)

print(f"\nStatistics:")
print(f"  Total unique accounts: {threshold_table['account_id'].nunique()}")
print(f"  Total periods analyzed: {len(threshold_table)}")
print(f"  Average threshold: {threshold_table['threshold_amt'].mean():.2f}")
print(f"  Median threshold: {threshold_table['threshold_amt'].median():.2f}")
print(f"  Max threshold: {threshold_table['threshold_amt'].max():.2f}")
print(f"  Min threshold: {threshold_table['threshold_amt'].min():.2f}")
print(f"  Std deviation: {threshold_table['threshold_amt'].std():.2f}")

# =====================================================================
# CORRECTED STEP 2.2 FOR MONTHLY REFERENCE POINTS
# =====================================================================
print("\n" + "="*70)
print("STEP 2.2 - MONTHLY REFERENCE POINTS (if applicable)")
print("="*70)

if AGGREGATION_LEVEL == 'daily':
    # Create monthly reference points
    step_2_5_daily_level_sorted = (
        step_daily_level
        .sort_values(['account_id', 'month_last_date', 'transaction_datetime'])
    )
    
    # Get first row per (account_id, month_last_date)
    d = (
        step_2_5_daily_level_sorted
        .drop_duplicates(subset=['account_id', 'month_last_date'], keep='first')
        [['account_id', 'customer_id', 'month_last_date']]
        .copy()
    )
    
    if DEBUG:
        print("\nDEBUG - d (first row per month):")
        print(d.head(10))
    
    # Prepare a2 (all daily transactions)
    a2 = step_daily_level.copy()
    
    # Cross join on account_id, customer_id
    merged_a2d = a2.merge(
        d,
        on=['account_id', 'customer_id'],
        how='left',
        suffixes=('_x', '_y')
    )
    
    if DEBUG:
        print(f"\nDEBUG - merged_a2d shape before filter: {merged_a2d.shape}")
        print(f"DEBUG - merged_a2d columns: {merged_a2d.columns.tolist()}")
    
    # Apply LOOKBACK_DAYS window filter
    # Use month_last_date_y (from d, the reference month-end)
    mask_lookback_monthly = (
        (merged_a2d['transaction_datetime'] >= merged_a2d['month_last_date_y'] - pd.Timedelta(days=LOOKBACK_DAYS)) &
        (merged_a2d['transaction_datetime'] <= merged_a2d['month_last_date_y'])
    )
    
    if DEBUG:
        print(f"DEBUG - rows passing {LOOKBACK_DAYS}-day mask: {mask_lookback_monthly.sum()}")
    
    # Remove duplicates and create final result
    step3_lookback_table_monthly = (
        merged_a2d
        .loc[mask_lookback_monthly]
        .drop_duplicates(
            subset=['account_id', 'customer_id', 'transaction_datetime', 'month_last_date_y'],
            keep='first'
        )
        .rename(columns={
            'total_daily_amount': 'lookbakc_amt',
            'month_last_date_y': 'month_last_date'
        })
        [['account_id', 'customer_id', 'transaction_datetime', 'lookbakc_amt', 'month_last_date']]
        .sort_values(['account_id', 'month_last_date', 'transaction_datetime'])
        .reset_index(drop=True)
    )
    
    print(f"\nSTEP 2.2 - Monthly reference lookback: {len(step3_lookback_table_monthly)} rows")
    print(step3_lookback_table_monthly.head(20))
    
    # Monthly threshold aggregation
    monthly_threshold = (
        step3_lookback_table_monthly
        .groupby(['account_id', 'month_last_date'], as_index=False)
        .agg(
            threshold_amt=('lookbakc_amt', 'sum'),
            transaction_count=('lookbakc_amt', 'count')
        )
    )
    
    print(f"\nMonthly threshold aggregation:")
    print(monthly_threshold.head(20))

else:  # Already monthly, no need for step 2.2
    print("Note: Aggregation level is already 'monthly', Step 2.2 not applicable.")

# =====================================================================
# EXPORT RESULTS
# =====================================================================
print("\n" + "="*70)
print("EXPORTING RESULTS")
print("="*70)

export_name = f"threshold_{TRANSACTION_TYPE}_{AGGREGATION_LEVEL}_{LOOKBACK_DAYS}d_{datetime.now().strftime('%Y%m%d_%H%M%S')}"

threshold_table.to_csv(f"{export_name}_thresholds.csv", index=False)
worst_case.to_csv(f"{export_name}_worst_case.csv", index=False)

print(f"\nFiles exported:")
print(f"  - {export_name}_thresholds.csv")
print(f"  - {export_name}_worst_case.csv")

print("\n✓ Script completed successfully!")

======================================================================
CONFIG: TYPE=DEBIT, LEVEL=daily, LOOKBACK=10 days
======================================================================

STEP 1 - Row count (DEBIT): 124570
Sample:
       transaction_id  account_id customer_id transaction_datetime  \
235831   TXN_00235831  ACC_000001  CUST_00001           2024-07-01
92771    TXN_00092771  ACC_000001  CUST_00001           2024-09-12
182883   TXN_00182883  ACC_000001  CUST_00001           2024-09-21
112646   TXN_00112646  ACC_000001  CUST_00001           2024-09-27
182691   TXN_00182691  ACC_000001  CUST_00001           2024-12-07
124896   TXN_00124896  ACC_000002  CUST_00002           2024-07-13
160340   TXN_00160340  ACC_000002  CUST_00002           2024-08-22
26943    TXN_00026943  ACC_000002  CUST_00002           2024-09-02
171058   TXN_00171058  ACC_000002  CUST_00002           2024-09-08
220744   TXN_00220744  ACC_000002  CUST_00002           2024-09-16

       transaction_type transaction_category  transaction_amount account_type  \
235831            DEBIT                 CASH            44281.22      SAVINGS
92771             DEBIT                   FX          1210456.35      SAVINGS
182883            DEBIT                 CASH            26207.81      SAVINGS
112646            DEBIT   INTERNATIONAL_WIRE          2165984.21      SAVINGS
182691            DEBIT                 CASH            34297.13      SAVINGS
124896            DEBIT                 RTGS          1035185.72      SAVINGS
160340            DEBIT                 NEFT          4090009.86      SAVINGS
26943             DEBIT                   FX          4808426.89      SAVINGS
171058            DEBIT   INTERNATIONAL_WIRE          3791352.28      SAVINGS
220744            DEBIT               CHEQUE          4445255.88      SAVINGS

       account_open_date account_status  ... income_bracket    kyc_status  \
235831        1979-10-02         ACTIVE  ...            <5L  KYC_COMPLETE
92771         1979-10-02         ACTIVE  ...            <5L  KYC_COMPLETE
182883        1979-10-02         ACTIVE  ...            <5L  KYC_COMPLETE
112646        1979-10-02         ACTIVE  ...            <5L  KYC_COMPLETE
182691        1979-10-02         ACTIVE  ...            <5L  KYC_COMPLETE
124896        1991-08-25         ACTIVE  ...            <5L  KYC_COMPLETE
160340        1991-08-25         ACTIVE  ...            <5L  KYC_COMPLETE
26943         1991-08-25         ACTIVE  ...            <5L  KYC_COMPLETE
171058        1991-08-25         ACTIVE  ...            <5L  KYC_COMPLETE
220744        1991-08-25         ACTIVE  ...            <5L  KYC_COMPLETE

       pep_flag sanction_flag internal_watchlist_flag customer_risk_rating  \
235831        N             N                       N                  LOW
92771         N             N                       N                  LOW
182883        N             N                       N                  LOW
112646        N             N                       N                  LOW
182691        N             N                       N                  LOW
124896        Y             N                       N                 HIGH
160340        Y             N                       N                 HIGH
26943         Y             N                       N                 HIGH
171058        Y             N                       N                 HIGH
220744        Y             N                       N                 HIGH

       dob_or_incorporation_date customer_segment str_filed_date  \
235831                1950-03-09           RETAIL            NaT
92771                 1950-03-09           RETAIL            NaT
182883                1950-03-09           RETAIL            NaT
112646                1950-03-09           RETAIL            NaT
182691                1950-03-09           RETAIL            NaT
124896                1938-06-09           RETAIL     2024-11-08
160340                1938-06-09           RETAIL     2024-11-08
26943                 1938-06-09           RETAIL     2024-11-08
171058                1938-06-09           RETAIL     2024-11-08
220744                1938-06-09           RETAIL     2024-11-08

       str_filed_flag
235831              0
92771               0
182883              0
112646              0
182691              0
124896              1
160340              1
26943               1
171058              1
220744              1

[10 rows x 25 columns]

STEP 1.5 - Aggregated to daily level: 119656 rows
   account_id customer_id transaction_datetime month_last_date  \
0  ACC_000001  CUST_00001           2024-07-01      2024-08-01
1  ACC_000001  CUST_00001           2024-09-12      2024-10-01
2  ACC_000001  CUST_00001           2024-09-21      2024-10-01
3  ACC_000001  CUST_00001           2024-09-27      2024-10-01
4  ACC_000001  CUST_00001           2024-12-07      2025-01-01
5  ACC_000002  CUST_00002           2024-07-13      2024-08-01
6  ACC_000002  CUST_00002           2024-08-22      2024-09-01
7  ACC_000002  CUST_00002           2024-09-02      2024-10-01
8  ACC_000002  CUST_00002           2024-09-08      2024-10-01
9  ACC_000002  CUST_00002           2024-09-16      2024-10-01

   total_daily_amount
0            44281.22
1          1210456.35
2            26207.81
3          2165984.21
4            34297.13
5          1035185.72
6          4090009.86
7          4808426.89
8          3791352.28
9          4445255.88

STEP 2 - Creating 10-day lookback join...
STEP 2 - Lookback rows created: 209382

STEP 3 - Threshold table created: 119656 rows
    account_id customer_id transaction_datetime  threshold_amt  trxn_count  \
0   ACC_000001  CUST_00001           2024-07-01       44281.22           1
1   ACC_000001  CUST_00001           2024-09-12     1210456.35           1
2   ACC_000001  CUST_00001           2024-09-21     1236664.16           2
3   ACC_000001  CUST_00001           2024-09-27     2192192.02           2
4   ACC_000001  CUST_00001           2024-12-07       34297.13           1
5   ACC_000002  CUST_00002           2024-07-13     1035185.72           1
6   ACC_000002  CUST_00002           2024-08-22     4090009.86           1
7   ACC_000002  CUST_00002           2024-09-02     4808426.89           1
8   ACC_000002  CUST_00002           2024-09-08     8599779.17           2
9   ACC_000002  CUST_00002           2024-09-16     8236608.16           2
10  ACC_000002  CUST_00002           2024-10-31     3471918.23           1
11  ACC_000002  CUST_00002           2024-11-02     6407473.77           2
12  ACC_000002  CUST_00002           2024-12-12      325035.26           1
13  ACC_000002  CUST_00002           2024-12-15     3124969.12           2
14  ACC_000002  CUST_00002           2024-12-28       14534.27           1
15  ACC_000003  CUST_00002           2024-07-11     3861967.64           1
16  ACC_000003  CUST_00002           2024-07-16     4882514.89           2
17  ACC_000003  CUST_00002           2024-07-20     4893027.07           3
18  ACC_000003  CUST_00002           2024-07-21     9230295.85           4
19  ACC_000003  CUST_00002           2024-08-25     3512660.43           1

         avg_amt     max_amt     min_amt
0   4.428122e+04    44281.22    44281.22
1   1.210456e+06  1210456.35  1210456.35
2   6.183321e+05  1210456.35    26207.81
3   1.096096e+06  2165984.21    26207.81
4   3.429713e+04    34297.13    34297.13
5   1.035186e+06  1035185.72  1035185.72
6   4.090010e+06  4090009.86  4090009.86
7   4.808427e+06  4808426.89  4808426.89
8   4.299890e+06  4808426.89  3791352.28
9   4.118304e+06  4445255.88  3791352.28
10  3.471918e+06  3471918.23  3471918.23
11  3.203737e+06  3471918.23  2935555.54
12  3.250353e+05   325035.26   325035.26
13  1.562485e+06  2799933.86   325035.26
14  1.453427e+04    14534.27    14534.27
15  3.861968e+06  3861967.64  3861967.64
16  2.441257e+06  3861967.64  1020547.25
17  1.631009e+06  3861967.64    10512.18
18  2.307574e+06  4337268.78    10512.18
19  3.512660e+06  3512660.43  3512660.43

======================================================================
WORST CASE POPULATION ANALYSIS
======================================================================

Top 20 accounts by total threshold amount:
      account_id  count_periods  total_threshold  avg_threshold  \
5269  ACC_006149             20     3.845994e+08   1.922997e+07
6358  ACC_007445             13     3.098859e+08   2.383737e+07
5     ACC_000007             14     2.997512e+08   2.141080e+07
5094  ACC_005940             13     2.751074e+08   2.116211e+07
6120  ACC_007160             30     2.315116e+08   7.717053e+06
1735  ACC_002033             18     2.197037e+08   1.220576e+07
1896  ACC_002223             26     2.092053e+08   8.046357e+06
2207  ACC_002569             23     2.089135e+08   9.083197e+06
3160  ACC_003690             16     2.087593e+08   1.304745e+07
4819  ACC_005626             13     2.052527e+08   1.578867e+07
3597  ACC_004198             26     2.030150e+08   7.808267e+06
1366  ACC_001595             20     1.939560e+08   9.697800e+06
1026  ACC_001202              9     1.919526e+08   2.132807e+07
7352  ACC_008637             28     1.915649e+08   6.841605e+06
6158  ACC_007208             29     1.912583e+08   6.595114e+06
8397  ACC_009847             23     1.867329e+08   8.118823e+06
733   ACC_000863             22     1.843211e+08   8.378232e+06
7915  ACC_009284             27     1.836736e+08   6.802724e+06
5205  ACC_006073             20     1.823414e+08   9.117069e+06
814   ACC_000955             25     1.796799e+08   7.187195e+06

      max_threshold  min_threshold  total_trxn_count
5269    28757972.23     3246408.80               115
6358    34991340.46     3049761.77                70
5       33303435.89     4006968.06                70
5094    29542287.59     9302848.39                76
6120    18506421.20      362835.99                83
1735    19572772.27     2125142.54                94
1896    18140030.68     2642506.53                73
2207    19794330.84      792870.46                60
3160    24477852.27     3607339.76                73
4819    23491650.22     4375142.37                64
3597    19945287.22       44833.96                70
1366    23432146.78     1674971.31                61
1026    38145977.65     6731226.97                45
7352    15333495.12      625301.08                78
6158    13446863.94     2301725.66                66
8397    17993156.37     1716708.95                56
733     26202744.21      281419.71                50
7915    14110615.40       21551.87                67
5205    24750057.32      147582.48                66
814     14872348.40     2149155.11                59

Worst case (highest single threshold):
        account_id customer_id transaction_datetime  threshold_amt  trxn_count
114025  ACC_009505  CUST_07619           2024-12-14    57771957.02           1
112511  ACC_009377  CUST_07510           2024-07-03    39782488.79           3
67447   ACC_005581  CUST_04476           2024-12-31    39228237.05           3
14770   ACC_001202  CUST_00966           2024-12-31    38145977.65           9
89707   ACC_007445  CUST_05951           2024-12-27    34991340.46           8
89704   ACC_007445  CUST_05951           2024-12-21    34173331.23           7
59      ACC_000007  CUST_00004           2024-12-20    33303435.89           6
89706   ACC_007445  CUST_05951           2024-12-25    32775085.96           7
89703   ACC_007445  CUST_05951           2024-12-20    32544317.79           7
89705   ACC_007445  CUST_05951           2024-12-24    32268664.26           7

Statistics:
  Total unique accounts: 8513
  Total periods analyzed: 119656
  Average threshold: 4332606.39
  Median threshold: 3917598.41
  Max threshold: 57771957.02
  Min threshold: 251.14
  Std deviation: 3037525.32

======================================================================
STEP 2.2 - MONTHLY REFERENCE POINTS (if applicable)
======================================================================

DEBUG - d (first row per month):
    account_id customer_id month_last_date
0   ACC_000001  CUST_00001      2024-08-01
1   ACC_000001  CUST_00001      2024-10-01
4   ACC_000001  CUST_00001      2025-01-01
5   ACC_000002  CUST_00002      2024-08-01
6   ACC_000002  CUST_00002      2024-09-01
7   ACC_000002  CUST_00002      2024-10-01
10  ACC_000002  CUST_00002      2024-11-01
11  ACC_000002  CUST_00002      2024-12-01
12  ACC_000002  CUST_00002      2025-01-01
15  ACC_000003  CUST_00002      2024-08-01

DEBUG - merged_a2d shape before filter: (662768, 6)
DEBUG - merged_a2d columns: ['account_id', 'customer_id', 'transaction_datetime', 'month_last_date_x', 'total_daily_amount', 'month_last_date_y']
DEBUG - rows passing 10-day mask: 41936

STEP 2.2 - Monthly reference lookback: 41936 rows
    account_id customer_id transaction_datetime  lookbakc_amt month_last_date
0   ACC_000001  CUST_00001           2024-09-21      26207.81      2024-10-01
1   ACC_000001  CUST_00001           2024-09-27    2165984.21      2024-10-01
2   ACC_000002  CUST_00002           2024-08-22    4090009.86      2024-09-01
3   ACC_000002  CUST_00002           2024-10-31    3471918.23      2024-11-01
4   ACC_000002  CUST_00002           2024-12-28      14534.27      2025-01-01
5   ACC_000003  CUST_00002           2024-08-25    3512660.43      2024-09-01
6   ACC_000003  CUST_00002           2024-09-30    3182529.09      2024-10-01
7   ACC_000003  CUST_00002           2024-10-25    3553456.37      2024-11-01
8   ACC_000003  CUST_00002           2024-11-21       1552.30      2024-12-01
9   ACC_000003  CUST_00002           2024-11-27     339578.07      2024-12-01
10  ACC_000003  CUST_00002           2024-12-26     135683.23      2025-01-01
11  ACC_000004  CUST_00003           2024-08-01    4423962.72      2024-08-01
12  ACC_000004  CUST_00003           2024-11-28    1647674.74      2024-12-01
13  ACC_000005  CUST_00003           2024-07-27    3712653.34      2024-08-01
14  ACC_000005  CUST_00003           2024-07-28     812765.83      2024-08-01
15  ACC_000005  CUST_00003           2024-09-21    2559828.48      2024-10-01
16  ACC_000005  CUST_00003           2024-09-23    2706165.90      2024-10-01
17  ACC_000007  CUST_00004           2024-12-23    4629688.71      2025-01-01
18  ACC_000007  CUST_00004           2024-12-26    2865941.09      2025-01-01
19  ACC_000007  CUST_00004           2024-12-28    2391907.82      2025-01-01

Monthly threshold aggregation:
    account_id month_last_date  threshold_amt  transaction_count
0   ACC_000001      2024-10-01     2192192.02                  2
1   ACC_000002      2024-09-01     4090009.86                  1
2   ACC_000002      2024-11-01     3471918.23                  1
3   ACC_000002      2025-01-01       14534.27                  1
4   ACC_000003      2024-09-01     3512660.43                  1
5   ACC_000003      2024-10-01     3182529.09                  1
6   ACC_000003      2024-11-01     3553456.37                  1
7   ACC_000003      2024-12-01      341130.37                  2
8   ACC_000003      2025-01-01      135683.23                  1
9   ACC_000004      2024-08-01     4423962.72                  1
10  ACC_000004      2024-12-01     1647674.74                  1
11  ACC_000005      2024-08-01     4525419.17                  2
12  ACC_000005      2024-10-01     5265994.38                  2
13  ACC_000007      2025-01-01    17092740.80                  6
14  ACC_000008      2024-08-01     7125672.29                  2
15  ACC_000008      2024-09-01      271984.58                  1
16  ACC_000008      2024-11-01     1793615.42                  1
17  ACC_000009      2024-08-01      911648.86                  1
18  ACC_000009      2024-09-01     5054168.66                  2
19  ACC_000009      2024-10-01     4921556.23                  1

======================================================================
EXPORTING RESULTS
======================================================================

Files exported:
  - threshold_DEBIT_daily_10d_20260203_005124_thresholds.csv
  - threshold_DEBIT_daily_10d_20260203_005124_worst_case.csv

✓ Script completed successfully!

In [5]:
threshold_table

,account_id,customer_id,transaction_datetime,threshold_amt,trxn_count,avg_amt,max_amt,min_amt
0,ACC_000001,CUST_00001,2024-07-01,44281.22,1,4.428122e+04,44281.22,44281.22
1,ACC_000001,CUST_00001,2024-09-12,1210456.35,1,1.210456e+06,1210456.35,1210456.35
2,ACC_000001,CUST_00001,2024-09-21,1236664.16,2,6.183321e+05,1210456.35,26207.81
3,ACC_000001,CUST_00001,2024-09-27,2192192.02,2,1.096096e+06,2165984.21,26207.81
4,ACC_000001,CUST_00001,2024-12-07,34297.13,1,3.429713e+04,34297.13,34297.13
...,...,...,...,...,...,...,...,...
119651,ACC_009979,CUST_08000,2024-12-08,2542689.40,1,2.542689e+06,2542689.40,2542689.40
119652,ACC_009979,CUST_08000,2024-12-09,2640648.40,2,1.320324e+06,2542689.40,97959.00
119653,ACC_009979,CUST_08000,2024-12-20,2508868.20,1,2.508868e+06,2508868.20,2508868.20
119654,ACC_009979,CUST_08000,2024-12-26,3756989.15,2,1.878495e+06,2508868.20,1248120.95
119655,ACC_009979,CUST_08000,2024-12-30,5932008.70,3,1.977336e+06,2508868.20,1248120.95

In [ ]:
import pandas as pd
import numpy as np

# -------------------------------------------------------------------
# STEP 0 – sanity check
# -------------------------------------------------------------------
step0 = (
    new_merged_data
    .loc[
        (new_merged_data['account_id'] == 'ACC_000001') &
        (new_merged_data['transaction_type'] == 'DEBIT')
    ,
        ['transaction_datetime', 'transaction_amount']
    ]
    .sort_values('transaction_datetime')
)

print("STEP 0 - sanity check (ACC_000001, DEBIT):")
print(step0.head(20))

# -------------------------------------------------------------------
# STEP 1 – static filter: only DEBIT transactions
# -------------------------------------------------------------------
step1_monthly = new_merged_data[new_merged_data['transaction_type'] == 'DEBIT'].copy()

print("\nSTEP 1 - row count (DEBIT only):", len(step1_monthly))
print("\nSTEP 1 - sample:")
print(
    step1_monthly
    .sort_values(['account_id', 'transaction_datetime'])
    .head(20)
)

# -------------------------------------------------------------------
# STEP 1.5 – grouping at daily level
# (Here you group by the full transaction_datetime in SQL; we mimic that)
# -------------------------------------------------------------------
step_2_5_daily_level = (
    step1_monthly
    .assign(
        month_last_date = step1_monthly['transaction_datetime'].dt.to_period('M').dt.to_timestamp('M') + pd.Timedelta(days=1)
        # SQL: DATEADD(day, 1, EOMONTH(transaction_datetime))
    )
    .groupby(['account_id', 'customer_id', 'transaction_datetime', 'month_last_date'], as_index=False)
    .agg(total_daily_amount=('transaction_amount', 'sum'))
)

print("\nSTEP 1.5 - daily level for ACC_000001:")
print(
    step_2_5_daily_level
    .loc[step_2_5_daily_level['account_id'] == 'ACC_000001']
    .sort_values('transaction_datetime')
)

# -------------------------------------------------------------------
# STEP 2.1 – lookback on 7 days (daily - transaction_datetime column)
# Left join step_2_5_daily_level (a) with step_2_5_daily_level (b)
# where account_id matches and b.transaction_datetime between
# a.transaction_datetime - 7 days and a.transaction_datetime
# -------------------------------------------------------------------
a = step_2_5_daily_level.rename(columns={
    'transaction_datetime': 'transaction_datetime_a',
    'total_daily_amount': 'total_daily_amount_a'
})
b = step_2_5_daily_level.rename(columns={
    'transaction_datetime': 'transaction_datetime_b',
    'total_daily_amount': 'total_daily_amount_b'
})

# Merge on account_id and customer_id (SQL uses account_id; you can decide
# whether to extend to customer_id as well; here we keep only account_id
# to match your SQL)
merged_ab = a.merge(
    b,
    on='account_id',
    suffixes=('_a', '_b'),
    how='left'
)

# Filter on the 7-day lookback window
mask_7d = (
    (merged_ab['transaction_datetime_b'] >= merged_ab['transaction_datetime_a'] - pd.Timedelta(days=7)) &
    (merged_ab['transaction_datetime_b'] <= merged_ab['transaction_datetime_a'])
)

step3_lookback_table = (
    merged_ab.loc[mask_7d, [
        'account_id',
        'customer_id_a',
        'transaction_datetime_a',
        'total_daily_amount_a',
        'total_daily_amount_b',
        'transaction_datetime_b'
    ]]
    .rename(columns={
        'customer_id_a': 'customer_id',
        'transaction_datetime_a': 'transaction_datetime',
        'total_daily_amount_a': 'total_daily_amount',
        'total_daily_amount_b': 'amount_lookback',
        'transaction_datetime_b': 'trxn_date_daily_level'
    })
    .sort_values(['account_id', 'transaction_datetime', 'trxn_date_daily_level'])
)

print("\nSTEP 2.1 - 7-day lookback for ACC_000001:")
print(
    step3_lookback_table
    .loc[step3_lookback_table['account_id'] == 'ACC_000001']
    .head(50)
)

# -------------------------------------------------------------------
# STEP 2.2 – lookback on 60 days (monthly - transaction_datetime)
# Logic:
#  - For each (account_id, month_last_date), find the first row by transaction_datetime
#    (rank_1 = 1).
#  - For each row a, join to rows d where a.account_id = d.account_id and
#    a.transaction_datetime between (d.month_last_date - 60 days) and d.month_last_date.
# -------------------------------------------------------------------

# First: compute rank_1 per (account_id, month_last_date)
step_2_5_daily_level_sorted = (
    step_2_5_daily_level
    .sort_values(['account_id', 'month_last_date', 'transaction_datetime'])
)
step_2_5_daily_level_sorted['rank_1'] = (
    step_2_5_daily_level_sorted
    .groupby(['account_id', 'month_last_date'])
    .cumcount() + 1
)

d = step_2_5_daily_level_sorted[step_2_5_daily_level_sorted['rank_1'] == 1].copy()
d = d.rename(columns={
    'transaction_datetime': 'transaction_datetime_d',
    'total_daily_amount': 'total_daily_amount_d'
})

a2 = step_2_5_daily_level.rename(columns={
    'transaction_datetime': 'transaction_datetime_a2',
    'total_daily_amount': 'total_daily_amount_a2'
})

merged_a2d = a2.merge(
    d[['account_id', 'month_last_date', 'transaction_datetime_d', 'total_daily_amount_d', 'rank_1']],
    on='account_id',
    how='left',
    suffixes=('', '_d')
)

mask_60d = (
    (merged_a2d['transaction_datetime_a2'] >= merged_a2d['month_last_date'] - pd.Timedelta(days=60)) &
    (merged_a2d['transaction_datetime_a2'] <= merged_a2d['month_last_date'])
)

step3_lookback_table_monthly = (
    merged_a2d.loc[mask_60d, [
        'account_id',
        'customer_id',
        'transaction_datetime_a2',
        'total_daily_amount_a2',
        'month_last_date',
        'rank_1'
    ]]
    .rename(columns={
        'transaction_datetime_a2': 'transaction_datetime',
        'total_daily_amount_a2': 'lookbakc_amt'  # keep the same name as in SQL
    })
    .sort_values(['account_id', 'month_last_date', 'transaction_datetime'])
)

print("\nSTEP 2.2 - rank_1 view for ACC_000001:")
print(
    step_2_5_daily_level_sorted
    .loc[step_2_5_daily_level_sorted['account_id'] == 'ACC_000001', 
         ['account_id', 'transaction_datetime', 'month_last_date', 'rank_1']]
    .sort_values(['account_id', 'month_last_date', 'transaction_datetime'])
)

print("\nSTEP 2.2 - step3_lookback_table_monthly for ACC_000001:")
print(
    step3_lookback_table_monthly
    .loc[step3_lookback_table_monthly['account_id'] == 'ACC_000001']
    .sort_values('month_last_date')
)

# -------------------------------------------------------------------
# STEP 3.1 – Daily threshold (7-day lookback)
# group by account_id, transaction_datetime, sum(amount_lookback)
# -------------------------------------------------------------------
daily_threshold = (
    step3_lookback_table
    .groupby(['account_id', 'transaction_datetime'], as_index=False)
    .agg(threshold_amt=('amount_lookback', 'sum'))
)

print("\nSTEP 3.1 - daily threshold for ACC_000001:")
print(
    daily_threshold
    .loc[daily_threshold['account_id'] == 'ACC_000001']
    .sort_values('transaction_datetime')
)

# -------------------------------------------------------------------
# STEP 3.2 – Monthly threshold (60-day lookback)
# group by account_id, month_last_date, sum(lookbakc_amt)
# -------------------------------------------------------------------
monthly_threshold = (
    step3_lookback_table_monthly
    .groupby(['account_id', 'month_last_date'], as_index=False)
    .agg(threshold_amt=('lookbakc_amt', 'sum'))
)

print("\nSTEP 3.2 - monthly threshold for ACC_000001:")
print(
    monthly_threshold
    .loc[monthly_threshold['account_id'] == 'ACC_000001']
    .sort_values('month_last_date')
)

# -------------------------------------------------------------------
# OPTIONAL: If you also want to reproduce your second SQL block
# (step2_monthly and step3_monthly) using the original "merged data"
# assuming new_merged_data is the same as [merged data] but with DEBIT filter removed.
# -------------------------------------------------------------------

# STEP 2 – 1-month lookback over all transactions (no DEBIT filter)
a_m = new_merged_data.rename(columns={
    'transaction_datetime': 'transaction_datetime_a',
    'transaction_amount': 'transaction_amount_a',
})
b_m = new_merged_data.rename(columns={
    'transaction_datetime': 'transaction_datetime_b',
    'transaction_amount': 'transaction_amount_b',
})

merged_m = a_m.merge(
    b_m[['account_id', 'transaction_datetime_b', 'transaction_amount_b']],
    on='account_id',
    how='left'
)

mask_1m = (
    (merged_m['transaction_datetime_b'] >= merged_m['transaction_datetime_a'] - pd.DateOffset(months=1)) &
    (merged_m['transaction_datetime_b'] <= merged_m['transaction_datetime_a'])
)

step2_monthly = (
    merged_m.loc[mask_1m, [
        'transaction_id',
        'account_id',
        'customer_id',
        'transaction_datetime_a',
        'transaction_amount_a',
        'transaction_amount_b',
        'transaction_datetime_b'
    ]]
    .rename(columns={
        'transaction_datetime_a': 'transaction_datetime',
        'transaction_amount_a': 'transaction_amount',
        'transaction_amount_b': 'amount_v1',
        'transaction_datetime_b': 'trxn_date_v1'
    })
    .sort_values(['account_id', 'transaction_datetime', 'trxn_date_v1'])
)

print("\nSTEP 2 (monthly) - row count:", len(step2_monthly))
print("\nSTEP 2 (monthly) - sample:")
print(step2_monthly.head(50))

# STEP 3 – aggregation: group by account_id and month (EOMONTH)
step3_monthly = (
    step2_monthly
    .assign(
        month_last_date = step2_monthly['transaction_datetime'].dt.to_period('M').dt.to_timestamp('M')
    )
    .groupby(['account_id', 'month_last_date'], as_index=False)
    .agg(sum_amount_v1=('amount_v1', 'sum'))
)

print("\nSTEP 3 (monthly) - row count:", len(step3_monthly))
print("\nSTEP 3 (monthly) - sample:")
print(step3_monthly.head(50))

ValueError: time data "21/12/2024" doesn't match format "%m/%d/%Y". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [ ]:
import numpy as np
import pandas as pd

# ==============================================================
# STEP 3.0 - CONFIG (Aggregation Lens + Boundary Strategy)
# ==============================================================
ENTITY_COLLAPSE = 'max'      # 'max', 'avg', 'p95', 'last'
TIME_LENS = 'full'           # 'full', 'daily', 'rolling_peak', 'sustained'
SUSTAINED_DAYS = 3           # used only if TIME_LENS in ('rolling_peak', 'sustained')

THRESHOLD_STRATEGY = 'percentile'   # 'percentile', 'absolute', 'top_n'
PERCENTILE = 99.0
ABSOLUTE_THRESHOLD = None    # used if strategy == 'absolute'
TOP_N = 100                  # used if strategy == 'top_n'

BUFFER_TYPE = 'hard'         # 'hard' or 'buffered'
BUFFER_BAND_PCT = 2.0        # only if buffered

STRESS_DELTAS_PCT = [-5, -2, -1, 1, 2, 5]

STABILITY_SAMPLES = 20
STABILITY_SAMPLE_FRAC = 0.75

# ==============================================================
# STEP 3.1 - Build Behavior Table from Step 2 (threshold_table)
# ==============================================================
# threshold_table is expected from your Step 2 script
# Columns expected: account_id, transaction_datetime, threshold_amt
if 'threshold_table' not in globals():
    raise ValueError("threshold_table not found. Run Step 2 first.")

behavior_df = threshold_table.rename(columns={
    'account_id': 'entity_id',
    'transaction_datetime': 'as_of_date',
    'threshold_amt': 'metric_value'
}).copy()

behavior_df['as_of_date'] = pd.to_datetime(behavior_df['as_of_date'], errors='coerce')
behavior_df['metric_value'] = pd.to_numeric(behavior_df['metric_value'], errors='coerce')
behavior_df = behavior_df.dropna(subset=['as_of_date', 'metric_value'])

# --------------------------------------------------------------
# Helpers
# --------------------------------------------------------------
def apply_time_lens(df, time_lens='full', sustained_days=3):
    time_lens = (time_lens or 'full').lower()
    base = df[['entity_id', 'as_of_date', 'metric_value']].copy()

    if time_lens == 'full':
        return base

    # daily collapse
    daily = (
        base.assign(day=base['as_of_date'].dt.floor('D'))
            .groupby(['entity_id', 'day'], as_index=False)['metric_value']
            .max()
            .rename(columns={'day': 'as_of_date'})
            .sort_values(['entity_id', 'as_of_date'])
    )

    if time_lens == 'daily':
        return daily

    # rolling_peak or sustained
    def roll_group(g):
        g = g.sort_values('as_of_date')
        vals = g['metric_value']
        roll_sum = vals.rolling(sustained_days, min_periods=1).sum()
        roll_avg = vals.rolling(sustained_days, min_periods=1).mean()
        all_non_zero = vals.rolling(sustained_days, min_periods=1).apply(lambda x: 1 if np.all(x != 0) else 0)
        if time_lens == 'rolling_peak':
            g['metric_value'] = roll_sum.values
        elif time_lens == 'sustained':
            g['metric_value'] = np.where(all_non_zero.values == 1, roll_avg.values, np.nan)
        return g

    rolled = daily.groupby('entity_id', as_index=False, group_keys=False).apply(roll_group)
    rolled = rolled.dropna(subset=['metric_value'])
    return rolled

def collapse_entity(df, entity_collapse='max'):
    entity_collapse = (entity_collapse or 'max').lower()
    g = df.groupby('entity_id')['metric_value']
    if entity_collapse == 'max':
        return g.max().reset_index(name='aggregated_value')
    if entity_collapse == 'avg':
        return g.mean().reset_index(name='aggregated_value')
    if entity_collapse == 'p95':
        return g.quantile(0.95).reset_index(name='aggregated_value')
    if entity_collapse == 'last':
        idx = df.sort_values('as_of_date').groupby('entity_id').tail(1)
        return idx[['entity_id', 'metric_value']].rename(columns={'metric_value': 'aggregated_value'})
    raise ValueError("Unsupported entity_collapse")

def ks_stat(a, b):
    a = np.asarray(a, dtype=float)
    b = np.asarray(b, dtype=float)
    a = a[np.isfinite(a)]
    b = b[np.isfinite(b)]
    if len(a) == 0 or len(b) == 0:
        return None
    data = np.concatenate([a, b])
    a_sorted = np.sort(a)
    b_sorted = np.sort(b)
    cdf_a = np.searchsorted(a_sorted, data, side='right') / len(a_sorted)
    cdf_b = np.searchsorted(b_sorted, data, side='right') / len(b_sorted)
    return float(np.max(np.abs(cdf_a - cdf_b)))

def j_curve(signal, labels, points=120):
    signal = np.asarray(signal, dtype=float)
    labels = np.asarray(labels, dtype=int)
    mask = np.isfinite(signal)
    signal = signal[mask]
    labels = labels[mask]
    if len(signal) == 0:
        return {'max_j': None, 'threshold': None}

    thresholds = np.quantile(signal, np.linspace(0, 1, points))
    pos = labels == 1
    neg = labels == 0
    if pos.sum() == 0 or neg.sum() == 0:
        return {'max_j': None, 'threshold': None}

    best_j = -1
    best_th = None
    for th in thresholds:
        tpr = (signal[pos] >= th).mean()
        fpr = (signal[neg] >= th).mean()
        j = tpr - fpr
        if j > best_j:
            best_j = j
            best_th = th
    return {'max_j': float(best_j), 'threshold': float(best_th)}

# ==============================================================
# STEP 3.1 - Population validated (aggregation lens applied)
# ==============================================================
lens_df = apply_time_lens(behavior_df, TIME_LENS, SUSTAINED_DAYS)
agg_df = collapse_entity(lens_df, ENTITY_COLLAPSE)

step3_1_summary = {
    'n_entities': int(len(agg_df)),
    'min': float(agg_df['aggregated_value'].min()),
    'max': float(agg_df['aggregated_value'].max()),
    'mean': float(agg_df['aggregated_value'].mean()),
    'median': float(agg_df['aggregated_value'].median())
}

print("STEP 3.1 - Population summary:", step3_1_summary)

# ==============================================================
# STEP 3.2 - Aggregation lens recorded
# ==============================================================
step3_2_lens = {
    'entity_collapse': ENTITY_COLLAPSE,
    'time_lens': TIME_LENS,
    'sustained_days': SUSTAINED_DAYS
}
print("STEP 3.2 - Aggregation lens:", step3_2_lens)

# ==============================================================
# STEP 3.3 - Boundary construction (threshold strategy)
# ==============================================================
values = agg_df['aggregated_value'].values
if THRESHOLD_STRATEGY == 'percentile':
    threshold_value = float(np.percentile(values, PERCENTILE))
elif THRESHOLD_STRATEGY == 'absolute':
    threshold_value = float(ABSOLUTE_THRESHOLD)
elif THRESHOLD_STRATEGY == 'top_n':
    threshold_value = float(np.sort(values)[-TOP_N]) if len(values) >= TOP_N else float(values.max())
else:
    raise ValueError("Unsupported strategy")

if BUFFER_TYPE == 'buffered':
    lower = threshold_value * (1 - BUFFER_BAND_PCT / 100.0)
    upper = threshold_value * (1 + BUFFER_BAND_PCT / 100.0)
else:
    lower = threshold_value
    upper = threshold_value

atl_entities = set(agg_df[agg_df['aggregated_value'] >= upper]['entity_id'])
btl_entities = set(agg_df[agg_df['aggregated_value'] < lower]['entity_id'])

step3_3_boundary = {
    'threshold_value': threshold_value,
    'lower': lower,
    'upper': upper,
    'atl_count': len(atl_entities),
    'btl_count': len(btl_entities)
}
print("STEP 3.3 - Boundary:", step3_3_boundary)

# ==============================================================
# STEP 3.4 - KS validation
# ==============================================================
label_map = agg_df.set_index('entity_id')['aggregated_value']
behavior_labeled = behavior_df.copy()
behavior_labeled['aggregated_value'] = behavior_labeled['entity_id'].map(label_map)

behavior_labeled['pop'] = np.where(
    behavior_labeled['aggregated_value'] >= upper, 'ATL',
    np.where(behavior_labeled['aggregated_value'] < lower, 'BTL', 'EXCLUDE')
)
atl_vals = behavior_labeled.loc[behavior_labeled['pop'] == 'ATL', 'metric_value'].values
btl_vals = behavior_labeled.loc[behavior_labeled['pop'] == 'BTL', 'metric_value'].values

step3_4_ks = {
    'ks_stat': ks_stat(atl_vals, btl_vals),
    'n_atl': int(len(atl_vals)),
    'n_btl': int(len(btl_vals))
}
print("STEP 3.4 - KS:", step3_4_ks)

# ==============================================================
# STEP 3.5 - Stress testing
# ==============================================================
base_ids = atl_entities
base_atl_count = max(1, len(base_ids))
base_volume = float(agg_df.loc[agg_df['entity_id'].isin(base_ids), 'aggregated_value'].abs().sum())

stress_results = []
for d in STRESS_DELTAS_PCT:
    th = upper * (1 + d / 100.0)
    ids = set(agg_df[agg_df['aggregated_value'] >= th]['entity_id'])
    enter = len(ids - base_ids)
    leave = len(base_ids - ids)
    churn_pct = (enter + leave) / base_atl_count * 100.0
    enter_pct = enter / base_atl_count * 100.0
    leave_pct = leave / base_atl_count * 100.0
    sym_ids = list(ids.symmetric_difference(base_ids))
    volume_churn = float(agg_df.loc[agg_df['entity_id'].isin(sym_ids), 'aggregated_value'].abs().sum())
    volume_churn_pct = (volume_churn / base_volume * 100.0) if base_volume else 0.0
    stress_results.append({
        'delta_pct': d,
        'entity_churn_pct': churn_pct,
        'volume_churn_pct': volume_churn_pct,
        'enter_pct': enter_pct,
        'leave_pct': leave_pct
    })

step3_5_stress = stress_results
print("STEP 3.5 - Stress results (first 3 rows):", step3_5_stress[:3])

# ==============================================================
# STEP 3.6 - J-statistic separation + stability
# ==============================================================
labels = np.where(behavior_labeled['pop'] == 'ATL', 1, np.where(behavior_labeled['pop'] == 'BTL', 0, -1))
mask = labels >= 0
signal = behavior_labeled.loc[mask, 'metric_value'].values
labels = labels[mask]

j_result = j_curve(signal, labels)

# Stability via bootstrap
j_samples = []
if len(signal) > 0:
    n = len(signal)
    sample_n = max(10, int(n * STABILITY_SAMPLE_FRAC))
    rng = np.random.default_rng(42)
    for _ in range(STABILITY_SAMPLES):
        idx = rng.choice(n, size=sample_n, replace=False)
        js = j_curve(signal[idx], labels[idx])
        if js['max_j'] is not None:
            j_samples.append(js['max_j'])

if j_samples:
    mean_j = float(np.mean(j_samples))
    std_j = float(np.std(j_samples))
    if std_j <= 0.02:
        stability_label = 'stable'
    elif std_j <= 0.05:
        stability_label = 'moderate'
    else:
        stability_label = 'fragile'
else:
    mean_j = None
    std_j = None
    stability_label = 'unknown'

step3_6_j = {
    'max_j': j_result['max_j'],
    'j_threshold': j_result['threshold'],
    'stability_mean_j': mean_j,
    'stability_std_j': std_j,
    'stability_label': stability_label
}
print("STEP 3.6 - J statistic:", step3_6_j)